Repository Seterator/seterator.ru, pull requests merged in 2019-11, with the labels that each got.

#13 Роли пользователей
  Rauthor/Controllers/AccountController.cs
  Rauthor/Controllers/Api/AccountController.cs
  Rauthor/Controllers/Api/CompetitionController.cs
  Rauthor/Controllers/JuryController.cs
  Rauthor/Controllers/ProfileController.cs
  Rauthor/DatabaseContext.cs
  Rauthor/GlobalSuppressions.cs
  Rauthor/Models/Poem.cs
  Rauthor/Models/Role.cs
  Rauthor/Models/UserProfile.cs
  Rauthor/Rauthor.csproj
  Rauthor/Services/FoulLanguageFilter.cs
  Rauthor/Services/ServicesExtensions.cs
  Rauthor/Services/ShitService.cs
  Rauthor/Startup.cs
  Rauthor/Views/Participant/Edit.cshtml
  Rauthor/Views/Participant/Index.cshtml
Labels: backend, enhancement

#24 Поле для ввода пароля в форме регистрации.
  Rauthor/Views/Account/Register.cshtml
Labels: frontend

#36 Юнит-тесты для операций через Entity Framework
  Rauthor.UnitTests/BasicDatabaseTests.cs
  Rauthor.UnitTests/DatabaseRelationsTests.cs
  Rauthor.UnitTests/Rauthor.UnitTests.csproj
  Rauthor.sln
Labels: backend

#38 Полностью переработан дизайн страницы создания конкурса.
  Rauthor/Views/Competition/Create.cshtml
  Rauthor/Views/Competition/Details.cshtml
  Rauthor/Views/Home/Index.cshtml
  Rauthor/Views/Shared/_Layout.cshtml
  Rauthor/wwwroot/css/Blocks/Banner.css
  Rauthor/wwwroot/css/Blocks/CreateCompetition.css
  Rauthor/wwwroot/css/Blocks/ImgSvg.css
  Rauthor/wwwroot/css/Blocks/ImgText.css
  Rauthor/wwwroot/css/Blocks/PersonalInfo.css
  Rauthor/wwwroot/css/Blocks/SocialIcons.css
  Rauthor/wwwroot/css/Competition.css
  Rauthor/wwwroot/img/Competition/email.svg
  Rauthor/wwwroot/img/Competition/minus.svg
  Rauthor/wwwroot/img/Competition/picture.svg
  Rauthor/wwwroot/img/Competition/plus.svg
Labels: enhancement, frontend

#46 Обновлен скрипт создания конкурса.
  Rauthor/Views/Competition/Create.cshtml
  Rauthor/wwwroot/js/Competition/create.js
Labels: frontend

#49 Обновление размеров иконок svg, доработка футера.
  Rauthor/Views/Competition/Create.cshtml
  Rauthor/Views/Shared/Footer.cshtml
  Rauthor/Views/Shared/Header.cshtml
  Rauthor/wwwroot/css/Blocks/ImgSvg.css
  Rauthor/wwwroot/css/Blocks/SocialIcons.css
  Rauthor/wwwroot/css/Footer.css
Labels: bug, frontend, hot

#54 Страница конкурса переписана по методологии БЭМ.
  Rauthor/Views/Competition/Details.cshtml
  Rauthor/Views/Home/Index.cshtml
  Rauthor/Views/Shared/_Layout.cshtml
  Rauthor/wwwroot/css/Account.css
  Rauthor/wwwroot/css/Blocks/Avatar.css
  Rauthor/wwwroot/css/Blocks/Banner.css
  Rauthor/wwwroot/css/Blocks/Btn.css
  Rauthor/wwwroot/css/Blocks/CompetitionConditions.css
  Rauthor/wwwroot/css/Blocks/CompetitionDetails.css
  Rauthor/wwwroot/css/Blocks/CompetitionItem.css
  Rauthor/wwwroot/css/Blocks/CompetitionPrizes.css
  Rauthor/wwwroot/css/Blocks/EventItem.css
  Rauthor/wwwroot/css/Blocks/ImgSvg.css
  Rauthor/wwwroot/css/Blocks/ImgText.css
  Rauthor/wwwroot/css/Blocks/Index.css
  Rauthor/wwwroot/css/Blocks/Jury.css
  Rauthor/wwwroot/css/Blocks/ParticipantItem.css
  Rauthor/wwwroot/css/Blocks/Participants.css
  Rauthor/wwwroot/css/Blocks/PersonalInfo.css
  Rauthor/wwwroot/css/Blocks/SocialIcons.css
  Rauthor/wwwroot/css/Blocks/UserItem.css
  Rauthor/wwwroot/img/Competition/document.svg
  Rauthor/wwwroot/img/Competition/link_1.svg
  Rauthor/wwwroot/img/Competition/share.svg
  Rauthor/wwwroot/img/Competition/time.svg
  Rauthor/wwwroot/js/Competition/GetDate.js
  Rauthor/wwwroot/js/Competition/Timer.js
Labels: frontend

#55 Api-контроллер для соревнований
  Rauthor/Controllers/Api/CompetitionController.cs
  Rauthor/Models/Competition.cs
  Rauthor/Rauthor.ruleset
  Rauthor/ViewModels/Api/Competition.cs
Labels: backend, enhancement

#57 Обновление тестов
  Rauthor.UnitTests/Controllers/Api/Account.cs
  Rauthor.UnitTests/Controllers/Api/Competition.cs
  Rauthor.UnitTests/Controllers/Api/Profile.cs
  Rauthor.UnitTests/Controllers/Database.cs
  Rauthor/Models/Competition.cs
Labels: backend, development
