Repository Seterator/seterator.ru, pull requests merged in 2019-12, with the labels that each got.

#59 Исправление ошибка маршрутизации в контроллере профилей
  Rauthor/Controllers/ProfileController.cs
Labels: backend, bug

#60 Призы за победу в соревновании.
  Rauthor.UnitTests/Controllers/Api/Competition.cs
  Rauthor.UnitTests/Controllers/Database.cs
  Rauthor.UnitTests/Database/BasicDatabaseTests.cs
  Rauthor.UnitTests/Database/DatabaseRelationsTests.cs
  Rauthor/Controllers/Api/CompetitionController.cs
  Rauthor/DatabaseContext.cs
  Rauthor/Models/Competition.cs
  Rauthor/Models/Prize.cs
  Rauthor/ViewModels/Api/Competition.cs
Labels: backend, enhancement

#61 Отображение конкурсов на главной через fetch запросы.
  Rauthor/Views/Home/Index.cshtml
  Rauthor/wwwroot/js/Competition/Timer.js
  Rauthor/wwwroot/js/Home/Index.js
Labels: frontend

#70 Исправлена ошибка маршрутизации (опять)
  Rauthor/Controllers/Api/RoutesController.cs
  Rauthor/Controllers/ProfileController.cs
  Rauthor/Startup.cs
  Rauthor/Views/Shared/Header.cshtml
Labels: bug, frontend

#71 Доработки в api соревнований
  Rauthor.UnitTests/Controllers/Api/Competition.cs
  Rauthor.UnitTests/Controllers/Database.cs
  Rauthor/Controllers/Api/CompetitionController.cs
  Rauthor/Models/Competition.cs
  Rauthor/Models/CompetitionRelJury.cs
  Rauthor/ViewModels/Api/Competition.cs
Labels: backend, hot

#66 Обновлена страница подачи заявки.
  Rauthor/Views/Participant/Become.cshtml
  Rauthor/Views/Shared/_Layout.cshtml
  Rauthor/wwwroot/css/Blocks/CompetitionItem.css
  Rauthor/wwwroot/css/Blocks/Form.css
  Rauthor/wwwroot/css/Blocks/ImgSvg.css
  Rauthor/wwwroot/css/Blocks/ParticipantBecome.css
  Rauthor/wwwroot/css/Participant_become.css
  Rauthor/wwwroot/js/Home/Index.js
  Rauthor/wwwroot/js/Participant/Become.js
Labels: frontend
