Repository Seterator/seterator.ru, pull requests merged in 2020-06, with the labels that each got.

#105 Очередная попытка перейти на dotnet 3.1
  .travis.yml
  .vscode/launch.json
  Seterator.UnitTests/Seterator.UnitTests.csproj
  Seterator/Controllers/JuryController.cs
  Seterator/Properties/launchSettings.json
  Seterator/Seterator.csproj
  Seterator/Startup.cs
  Seterator/appsettings.json
  deploy.sh
Labels: WIP, backend, development, enhancement

#107 Обновлений сценариев для доставки на новый сервер
  Seterator/post-build.ps1
  deploy.sh
Labels: WIP, infrastructure

#110 Добавлены точки входа для каждой из страниц
  Seterator/Views/Account/Main.cshtml
  Seterator/Views/Competition/Create.cshtml
  Seterator/Views/Competition/Details.cshtml
  Seterator/Views/Competition/Update.cshtml
  Seterator/Views/Home/Index.cshtml
  Seterator/Views/Home/Privacy.cshtml
  Seterator/Views/Jury/Assessment.cshtml
  Seterator/Views/Participant/Become.cshtml
  Seterator/Views/Poem/Details.cshtml
  Seterator/Views/Profile/Index.cshtml
  Seterator/Views/Shared/_Layout.cshtml
  Seterator/webpack.config.js
  Seterator/webpack.dev.config.js
  Seterator/wwwroot/components/App.vue
  Seterator/wwwroot/js/Pages/Account/Index.js
  Seterator/wwwroot/js/Pages/Competition/Create.js
  Seterator/wwwroot/js/Pages/Competition/Details.js
  Seterator/wwwroot/js/Pages/Competition/Update.js
  Seterator/wwwroot/js/Pages/Home/Index.js
  Seterator/wwwroot/js/Pages/Home/Privacy.js
  Seterator/wwwroot/js/Pages/Jury/Assessment.js
  Seterator/wwwroot/js/Pages/Layout/Layout.js
  Seterator/wwwroot/js/Pages/Participant/Become.js
  Seterator/wwwroot/js/Pages/Poem/Details.js
  Seterator/wwwroot/js/Pages/Profile/Index.js
Labels: development, frontend

#112 Интеграция GithubActions
  .github/workflows/dotnet-core.yml
Labels: development, wontfix

#111 Фикс .gitignore
  .gitignore
  Seterator/webpack.config.js
  Seterator/webpack.dev.config.js
Labels: bug

#115 Настрока приложения для работы с Nginx в качестве прокси-сервера
  Seterator/Program.cs
  Seterator/Startup.cs
  Seterator/appsettings.Development.json
  Seterator/appsettings.Production.json
Labels: backend, enhancement

#119 Обновлен Футер
  Seterator/Views/Shared/Footer.cshtml
  Seterator/Views/Shared/_Layout.cshtml
  Seterator/wwwroot/components/Footer/Footer.vue
  Seterator/wwwroot/css/Footer.css
  Seterator/wwwroot/img/Social icons/Orange/telegram.svg
  Seterator/wwwroot/img/banks-icons/mastercard.svg
  Seterator/wwwroot/img/banks-icons/tinkoff.gif
  Seterator/wwwroot/img/banks-icons/visa.svg
  Seterator/wwwroot/js/Pages/Layout/Layout.js
Labels: frontend
